include ../Makefile.head
default:all

####
DIRS=TipsManager\
	SortManager\
	SwordMeansOffer\
	ProcessManager\
	LeetcodeManager\
	DataStructure\
####

build: clean all 

####
include ../Makefile.tail
