#ifndef UNION_ERROR_H
#define UNION_ERROR_H


enum UnionLicenseErr {
	ULERR_NO_PNAME_FILE = 0xF01,              //无法读取系统名称
	ULERR_NO_UUID_FILE,                       //无法读取系统ID
	ULERR_MAC_GET_IF,                         //无法读取网卡MAC地址列表
	ULERR_MAC_SOCK,                           //无法创建socket
	ULERR_MAC_IOCTL,                          //无法进行IOCTL操作
	ULERR_MAC_MAX_NUM,                        //网卡数量超出最大限制
	ULERR_ANALY_NO_CLEAR_DATA,                //输入明文license数据为空
	ULERR_ANALY_FIELD_NUM,                    //license明文数据域个数错误
	ULERR_ANALY_HWINFO_MAXLEN,                //license明文数据HWINFO长度错误
	ULERR_ANALY_ATVTIMES_FORMAT,              //license明文数据激活次数格式错误
	ULERR_ANALY_AUTHINFO_MAXLEN,              //license明文数据授权信息长度错误
	ULERR_ANALY_HASH_MAXLEN,                  //license明文数据HASH数据长度错误
	ULERR_ANALY_HASH_CHEK,					  //license明文数据HASH校验不匹配
	ULERR_NO_LICENSE_FILE,                    //license文件不存在或不能以读方式打开license文件
	ULERR_LICENSE_FILE_MAXSIZE,               //license文件大小超出上限
	ULERR_LICENSE_FILE_WRITE,                  //不能以写方式打开License文件
	ULERR_ANALY_NO_ACTIVE_TIMES,              //硬件信息(含激活次数)中缺少激活次数信息
	ULERR_ANALY_HWINFO_FIELD_NUM,             //硬件信息(含激活次数)中硬件信息域个数错误
	ULERR_ANALY_HWINFO_PNAME_MAXLEN,          //硬件信息(含激活次数)中硬件信息域个数错误
	ULERR_ANALY_HWINFO_PUUID_MAXLEN,          //硬件信息(含激活次数)中硬件信息域个数错误
	ULERR_ANALY_HWINFO_NOMATCH,               //license明文数据中的HWINFO与设备不匹配
};

enum UnionSynchErr {
	USYCERR_CONN_ERR = 0xE01,
	USYCERR_RES_INCOMPLETE,         //应答信息节点不存在或缺少errcode属性
	USYCERR_RES_ATTR_INCPL,         //应答信息中缺少属性
	USYCERR_REQ_INCOMPLETE,         //请求信息节点不存在或缺少属性
	USYCERR_REQ_ATTR_INCPL,         //请求信息中缺少属性
	USYCERR_RAND_LENTH_ERR,         //随机数长度错误
	USYCERR_XMLCREATE_ERR,			//无法创建XML数据结构
	USYCERR_XMLLENTH_MAX,			//xml数据超过了最大长度(64KB)
	USYCERR_INIT_CHKCODE_ERR,	    //初始化请求应答校验码错误
	USYCERR_INIT_RANDM_LEN_ERR,	    //初始化请求应答随机数长度错误
	USYCERR_REQ_UNKNOWN,	        //未识别的请求类型
	USYCERR_REQ_CHK_ENCLEN,	        //密钥校验密文值长度错误
	USYCERR_REQ_CHK_ENCCHK,	        //密钥校验密文值校验错误
	USYCERR_REQ_INITCLG_ENCCHK,	    //密钥初始化挑战校验密文值错误
	USYCERR_MEM_ALLOC_ERR,	        //没有足够的计算资源
	USYCERR_ACC_CHK_INVALID,	    //帐户口令校验错误
	USYCERR_ACC_ADD_EXSIT,	        //帐户添加错误，帐户已存在
	USYCERR_ACC_NO_EXSIT,	        //帐户改密/删除错误，帐户不存在
	USYCERR_ACC_PSWD_FORMAT,	    //帐户改密,新密码不符合密码规则
	USYCERR_ACC_PSWD_QUERY,	        //业务应用没有查询帐户口令的权限
	USYCERR_ACC_APP_CUSTOM = 0xE50,	//业务应用自定义的错误类型
};

enum {
	UWINERR_INVALID_PARAM = 0x601,
	UWINERR_SOCKET_FAILED,
	UWINERR_ACCESS_DENIED,
	UWINERR_INVALID_COMPUTER,
	UWINERR_NOT_PRIMARY,
	UWINERR_GROUP_EXISTS,
	UWINERR_USER_EXISTS,
	UWINERR_PASS_TOO_SHORT,
	UWINERR_USER_NOT_FOUND,
	UWINERR_INVALID_PASS,
	UWINERR_GROUP_NOT_FOUND,
	UWINERR_NO_SUCH_MEMBER,
	UWINERR_MEMBER_IN_ALIAS,
	UWINERR_INVALID_MEMBER,
	UWINERR_MORE_DATA,
	UWINERR_CONNECT_FAILED,
	UWINERR_READ_SOCKET,
	UWINERR_WRITE_SOCKET,
	UWINERR_MALLOC_FAILED,
	UWINERR_LAST_ADMIN,
	UWINERR_BAD_PASSWORD,
	UWINERR_UNSUPPORTED_TYPE,
	UWINERR_GEN_RAND_PASS_FAILED,
	UWINERR_TRUST_FAILED,
	UWINERR_STATUS_FORBIDDEN,
	UWINERR_SMB_INVALID_ARGU = 0x681,
	UWINERR_SMB_TERMINATE_IN_ADVANCE,
	UWINERR_SMB_TIMEOUT,
	UWINERR_SMB_NEWPASS_MISMATCH,
	UWINERR_SMB_LOGON_FAILED,
	UWINERR_SMB_CONNECT_FAILED,
	UWINERR_SMB_ACCESS_DENIED,
	UWINERR_SMB_GEN_RAND_PASS_FAILED,
	UWINERR_SMB_TRUST_FAILED,
	UWINERR_UNKNOWN,
};

enum {
	UODBCERR_ALLOC_ENV_HANDLE = 0x701,
	UODBCERR_ALLOC_DBC_HANDLE,
	UODBCERR_DRIVER_CONNECT,
	UODBCERR_ALLOC_STATE_HANDLE,
	UODBCERR_UNKNOWN_DB_TYPE,
	UODBCERR_UNKNOWN_OPER_TYPE,
	UODBCERR_ODBC_EXEC,
	UODBCERR_GEN_RAND_PASS_FAILED,
	UODBCERR_TRUST_FAILED,
	UODBCERR_INVALID_PARAM,
	UODBCERR_NO_ADMINISTRATOR,
	UODBCERR_STATUS_FORBIDDEN,
	UODBCERR_NOT_ADMINISTRATOR,
};

enum {
	UNION_ACC_OPER_NOT_SUPPORT = 0x801,   //帐户不支持的业务类型
	UNION_ACC_OPER_NOT_CONFIG,            //帐户所在资源未配置服务端口/通信密码
	UNION_VCENTER_AUTHMODE_FAILED,		  //未勾选指定的认帐方式
};

enum {                                                                    
	UNION_READ_CSSP_STATUS_FAILED = 0x901,  //读取CSSP加解密开关失败      
	UNION_READ_CSSP_KEYNAME_FAILED,         //读取CSSP加解密的密钥名失败
	UNION_NO_CONFIG_CSSP_KEYNAME,           //未配置CSSP加解密的密钥名      
	UNION_CSSP_KEYNAME_NOT_EXIST,           //密钥名不存在
	UNION_CSSP_CONNECT_FAILED,              //CSSP连接失败 
	UNION_SYSID_OR_APPID_UNDEFINED,         //系统ID或应用ID未定义
	UNION_CLIENTIP_NO_AUTHORIZED,           //客户端IP未被CSSP授权
	UNION_DECRYPT_FAILED,                   //解密失败
};   

#define UNION_OPERATE_SUCCESS 0x0

#define UNION_ARGU_ERR 0x01
#define UNION_DATA_FMT_ERR 0x02
#define UNION_DB_CHARACTE_ERR 0x03
#define UNION_DB_SYNTAX_ERR 0x04
#define UNION_DB_TABLE_NOT_EXIST 0x05
#define UNION_DB_COL_NOT_EXIST 0x06
#define UNION_DB_FOREIGN_KEY_ERR 0x07
#define UNION_DB_UNIQUE_KEY_ERR 0x08
#define UNION_DB_TABLE_LOCKED 0x09
#define UNION_XML_NODE_NOT_EXIST 0x0A
#define UNION_XML_NODE_NOT_UNIQUE 0x0B
#define UNION_XML_NODE_INVAILD 0x0C
#define UNION_XML_ATTRIBUTE_NOT_EXIST 0x0D
#define UNION_XML_ATTRIBUTE_INVAILD 0x0E
#define UNION_XML_DATA_INVAILD 0x0F
#define UNION_XML_FILE_NOT_EXIST 0x10
#define UNION_XML_PARSE_ERR 0x11
#define UNION_XML_FILE_CREATE_ERR 0x12
#define UNION_XML_NODE_CREATE_ERR 0x13
#define UNION_XML_PATH_NOT_EXIST 0x14
#define UNION_ARGU_DATA_TYPE_ERR 0x15
#define UNION_OPER_TYPE_ERR 0x16
#define UNION_USER_EXIST 0x17
#define UNION_USER_NO_ORGUNIT 0x18
#define UNION_EVENT_MODULE_NOT_MATCH 0x19
#define UNION_USER_NO_EXIST 0x1A
#define UNION_ORG_NO_EXIST 0x1B
#define UNION_ORG_EXIST 0x1C
#define UNION_ORG_LEAST_LEVEL 0x1D
#define UNION_ORG_PERMIT_DENY 0x1E
#define UNION_ORG_MAX_NUM 0x1F
#define UNION_USER_PERMIT_DENY 0x20
#define UNION_ORG_DELETE_DENY 0x21
#define UNION_MAST_HSMGRP_DELETE_DENY 0x22
#define UNION_SOCK_LISTEN_ERR 0x23
#define UNION_SOCK_ACCEPT_ERR 0x24
#define UNION_SOCK_WRITE_ERR 0x25
#define UNION_SOCK_READ_ERR 0x26
#define UNION_TASK_TERMINAL_NO_EXIST 0x27
#define UNION_TASK_APPLICATION_NO_EXIST 0x28
#define UNION_TASK_TERMINAL_USING 0x29
#define UNION_TASK_APPLICATION_USING 0x2A
#define UNION_TERMINAL_NO_EXIST 0x2B
#define UNION_APPLICATION_NO_EXIST 0x2C
#define UNION_OBJECT_NO_EXIST 0x2D
#define UNION_TASK_STATUS_NO_EXIST 0x2E
#define UNION_TASK_NO_EXIST 0x2F
#define UNION_APPROVAL_NO_EXIST 0x30
#define UNION_SOCK_CONNECT_ERR 0x31
#define UNION_KEYVALUE_CKECKVALUE_UNMATCH 0x32
#define UNION_HSM_HSMGRP_MKNOTSAME 0x33
#define UNION_FOREIGN_APPLICATION 0x34
#define UNION_HSM_FOREIGN 0x35
#define UNION_USER_UNDEFINE_ROLE 0x36
#define UNION_PRINTFMT_USED 0x37
#define UNION_CANNOT_ADD_USER 0x38
#define UNION_KEY_GEN_ERR 0x39
#define UNION_BUSINESS_USE_HSM 0x3A
#define UNION_BUSINESS_FOREIGN_APP 0x3B
#define UNION_HSM_CONNECT_FAIL 0x3C
#define UNION_HSM_MSGLEN_ERR 0x3D
#define UNION_NO_HAVE_HSM 0x3E
#define UNION_USER_DELETE_ERR 0x3F
#define UNION_TASK_TERMINAL_EXIST 0x40
#define UNION_TASK_APPLICATION_EXIST 0x41
#define UNION_ORG_DELETE_ERR 0x42
#define UNION_ROLE_NO_EXIST 0x43
#define UNION_TASK_OPER_NO_EXIST 0x44
#define UNION_TASK_OPER_EXIST 0x45
#define UNION_KEYVALUE_LENGTH_ERR 0x46
#define UNION_KEYTYPE_INSERT_ERR 0x47
#define UNION_KEYTYPE_DELETE_ERR 0x48
#define UNION_PERMIT_CHANGE 0x49
#define UNION_MODULE_NO_EXIST 0x5A
#define UNION_MODULE_EXIST 0x5B
#define UNION_ROLE_EXIST 0x5C
#define UNION_CODE_OVER_DUE 0x5D
#define UNION_POLICY_NO_EXIST 0x5E
#define UNION_POLICY_EXIST 0x5F
#define UNION_ACCOUNTLEVEL_NO_EXIST 0x60
#define UNION_OPERPWD_NO_EXIST 0x61
#define UNION_OPERPWD_EXIST 0x62
#define UNION_BUSINESS_NO_EXIST 0x63
#define UNION_BUSINESS_EXIST 0x64
#define UNION_OPERATE_NO_EXIST 0x65
#define UNION_OPERATE_EXIST 0x66
#define UNION_EVENT_NO_EXIST 0x67
#define UNION_EVENT_EXIST 0x68
#define UNION_OPERATIONTYPE_NO_EXIST 0x69
#define UNION_OPERATIONTYPE_EXIST 0x6A
#define UNION_REPAIR_CODE_ERR 0x6B
#define UNION_DEVICE_NO_EXIST 0x6C
#define UNION_DEVICE_EXIST 0x6D
#define UNION_PROTOCOL_NO_EXIST 0x6E
#define UNION_PROTOCOL_EXIST 0x6F
#define UNION_OS_NO_EXIST 0x70
#define UNION_OS_EXIST 0x71
#define UNION_EBOX_CHECK_ERR 0x72
#define UNION_EBOX_CREATE_ERR 0x73
#define UNION_EBOX_EXISTING 0x74

#define UNION_MEM_DEPLETE 0x101
#define UNION_PERMIT_DENY 0x102
#define UNION_DB_CONN_ERR 0x103
#define UNION_DB_IP_ERR 0x104
#define UNION_DB_PORT_ERR 0x105
#define UNION_DB_USER_PWD_ERR 0x106
#define UNION_DB_SOCK_ERR 0x107
#define UNION_DB_QUERY_ERR 0x108
#define UNION_DB_QUERY_NULL 0x109
#define UNION_DISK_NO_ENOUGH 0x10A
#define UNION_OPER_PART_SUCCESS 0x10B
#define UNION_OPER_ALL_FAILURE 0x10C
#define UNION_DB_INSERT_ERR 0x10D
#define UNION_DB_DELETE_ERR 0x10E
#define UNION_DB_UPDATE_ERR 0x10F
#define UNION_NTP_CONFIG_ERROR 0x110
#define UNION_REPEAT_OPERATE_ERROR 0x111
#define UNION_DB_UNKNOWN 0x112
#define UNION_DB_COL_NOTNULL 0x113
#define UNION_VERSION_CHECK_FAILED 0x114
#define UNION_DBVERSION_CHECK_FAILED 0x115
#define UNION_FSVERSION_CHECK_FAILED 0x116
#define UNION_DBUPDATE_FAILED 0x117
#define UNION_XMLUPDATE_FAILED 0x118
#define UNION_FILE_REPLACE_FAILED 0x119
#define UNION_SELF_SCRIPTE_FAILED 0x11A
#define UNION_PATCH_DECRYPT_FAILED 0x11B
#define UNION_PATCH_UPGRADE_FAILED 0x11C
#define UNION_ACCOUNT_INGROUP_NOTNULL 0x11D
#define UNION_ACCOUNT_LIST_DEL 0x11F


#define UNION_USER_INVAILD 0x401
#define UNION_AUTH_NOT_MATCH 0x402
#define UNION_USER_NOT_ACTIVE 0x403
#define UNION_PASS_FAILED 0x404
#define UNION_NO_NEED_PWD 0x405
#define UNION_TASK_LOCKED 0x406
#define UNION_TASK_STATUS_ERROR 0x407
#define UNION_USER_EXPIRED_TIME 0x408
#define UNION_USER_PWD_ERR 0x409
#define UNION_OPER_PWD_ERR 0x40A
#define UNION_ZMK_CHECK_ERR 0x40B
#define UNION_ZMK_FIND_ERR 0x40C
#define UNION_LICENSE_UNAUTHORIZED 0x40D
#define UNION_LICENSE_APP_OVER_LIMIT 0x40E
#define UNION_LICENSE_KEY_OVER_LIMIT 0x40F
#define UNION_LICENSE_TER_OVER_LIMIT 0x410
#define UNION_FORCE_CHANGE_PASSWORD 0x411
#define UNION_USER_LOCKED 0x412
#define UNION_USER_NO_APPROVED 0x413
#define UNION_USER_FORBIDDEN  0x414
#define UNION_USER_LOGIN_PASSWORD_ERROR 0x415
#define UNION_USER_NEWPWD_OLDPWD_SAME 0x416
#define UNION_USER_OVERDUE           0x417
#define UNION_DOMAIN_ARGU_ERR        0x418
#define UNION_USER_CONTRACT_EXPIRED  0x419
#define UNION_TOKEN_IS_NOT_EXIST     0x41A
#define UNION_TOKEN_HAS_BINDED       0x41B
#define UNION_BIND_OTHER_TOKEN       0x41C
#define UNION_DEL_TOKEN_ERR          0x41D
#define UNION_OBJECT_NUM_OVER_LIMIT 0x41E
#define UNION_OTPS_CONNECT_FAILED 0x41F
#define UNION_SEEDFILE_FORMAT_ERROR 0x420
#define UNION_FIRMKEY_NOT_EXIST 0x421
#define UNION_OTPS_KEK_NOT_EXIST 0x422
#define UNION_CSSP_CHECK_FAILD 0x423


#define UNION_COMMON_CONN_ERR 0x501
#define UNION_CHECK_EXECTIMES_ERR 0x502
#define UNION_ALL_FAILED 0x503
#define UNION_PARTIAL_FAILED 0x504
#define UNION_CHECK_VALID_ERR 0x505
#define UNION_GENERATE_EXCEL_FAILED 0x506
#define UNION_WORKNOTE_LOCK_FAILED 0x507
#define UNION_WORKNOTE_UNLOCK_FAILED 0x508
#define UNION_DYCODECHECK_FAILD 0x509
#define UNION_EXISTPWD_NOT_APPROPRIATE 0x50A

#ifdef __cplusplus
extern "C" {
#endif
const char *UnionGetErrMsg(int ErrNo);
const char *UnionGetErrDetail(int ErrNo);
#ifdef __cplusplus
}
#endif

#endif
